const data = {
  freeGames: {
    current: [
      {
        title: "Epistory - Typing Chronicles",
        id: "63352c1c0eed4ab9a640dafee08eff54",
        namespace: "6a6d54e5b4ef4fb0b3dad1d02a320376",
        description:
          "Epistory immerses you in an atmospheric game where you play a girl riding a giant fox who fights an insectile corruption from an origami world. As you progress and explore this world, the story literally unfolds and the mysteries of the magic power of the words are revealed.",
        effectiveDate: "2023-01-19T16:00:00.000Z",
        offerType: "BASE_GAME",
        expiryDate: null,
        status: "ACTIVE",
        isCodeRedemptionOnly: false,
        keyImages: [
          {
            type: "OfferImageWide",
            url: "https://cdn1.epicgames.com/spt-assets/2fe270709f944fc398851454cf476f95/epistory-typing-adventure-1t9zx.jpg",
          },
          {
            type: "OfferImageTall",
            url: "https://cdn1.epicgames.com/spt-assets/2fe270709f944fc398851454cf476f95/epistory--typing-chronicles-19b5z.png",
          },
          {
            type: "Thumbnail",
            url: "https://cdn1.epicgames.com/spt-assets/2fe270709f944fc398851454cf476f95/epistory--typing-chronicles-19b5z.png",
          },
        ],
        seller: {
          id: "o-yw5ga5z854qs64ld82qey3dz2d7z32",
          name: "Plug In Digital SAS",
        },
        productSlug: null,
        urlSlug: "e627683054b14bf1b1c7f4e8769eca54",
        url: null,
        items: [
          {
            id: "93edcd42adeb4228bd5912f775cf586a",
            namespace: "6a6d54e5b4ef4fb0b3dad1d02a320376",
          },
        ],
        customAttributes: [
          {
            key: "autoGeneratedPrice",
            value: "false",
          },
          {
            key: "isManuallySetViewableDate",
            value: "true",
          },
          {
            key: "isManuallySetPCReleaseDate",
            value: "true",
          },
          {
            key: "isBlockchainUsed",
            value: "null",
          },
        ],
        categories: [
          {
            path: "freegames",
          },
          {
            path: "games/edition",
          },
          {
            path: "games",
          },
          {
            path: "games/edition/base",
          },
        ],
        tags: [
          {
            id: "1381",
          },
          {
            id: "1370",
          },
          {
            id: "9547",
          },
          {
            id: "1117",
          },
        ],
        catalogNs: {
          mappings: [
            {
              pageSlug: "epistory-typing-chronicles-445794",
              pageType: "productHome",
            },
          ],
        },
        offerMappings: [
          {
            pageSlug: "epistory-typing-chronicles-445794",
            pageType: "productHome",
          },
        ],
        price: {
          totalPrice: {
            discountPrice: 0,
            originalPrice: 1499,
            voucherDiscount: 0,
            discount: 1499,
            currencyCode: "USD",
            currencyInfo: {
              decimals: 2,
            },
            fmtPrice: {
              originalPrice: "$14.99",
              discountPrice: "0",
              intermediatePrice: "0",
            },
          },
          lineOffers: [
            {
              appliedRules: [
                {
                  id: "7ce4ff8d242f418b9380802c67d0e735",
                  endDate: "2023-01-26T16:00:00.000Z",
                  discountSetting: {
                    discountType: "PERCENTAGE",
                  },
                },
              ],
            },
          ],
        },
        promotions: {
          promotionalOffers: [
            {
              promotionalOffers: [
                {
                  startDate: "2023-01-19T16:00:00.000Z",
                  endDate: "2023-01-26T16:00:00.000Z",
                  discountSetting: {
                    discountType: "PERCENTAGE",
                    discountPercentage: 0,
                  },
                },
              ],
            },
          ],
          upcomingPromotionalOffers: [],
        },
      },
    ],
    upcoming: [
      {
        title: "Adios",
        id: "7334a6f04f5b47218e691f805891bc5d",
        namespace: "a3dd9f3da8ec49c7b25dec42cce2ec46",
        description:
          "A pig farmer decides he no longer wants to dispose of bodies for the mob. What follows is a discussion between him and his would-be killer.",
        effectiveDate: "2021-06-29T04:00:00.000Z",
        offerType: "BASE_GAME",
        expiryDate: null,
        status: "ACTIVE",
        isCodeRedemptionOnly: false,
        keyImages: [
          {
            type: "OfferImageWide",
            url: "https://cdn1.epicgames.com/spt/e8e605d4-bd25-48d7-b99c-c8df348c9d81/adios-offer-41329995.jpg",
          },
          {
            type: "OfferImageTall",
            url: "https://cdn1.epicgames.com/spt/0e7cbbb0-a281-4c00-8538-7eb946666d84/download-adios-offer-3bab1685.jpg",
          },
          {
            type: "Thumbnail",
            url: "https://cdn1.epicgames.com/spt/0e7cbbb0-a281-4c00-8538-7eb946666d84/download-adios-offer-3bab1685.jpg",
          },
        ],
        seller: {
          id: "o-g7mfghfrudhwtc3xa4qm9aeyfwr3q4",
          name: "Mischief LLC",
        },
        productSlug: null,
        urlSlug: "4ba7673d57a34b5a9f2d697d207b674b",
        url: null,
        items: [
          {
            id: "a152b17b903048a7a6d318738392285a",
            namespace: "a3dd9f3da8ec49c7b25dec42cce2ec46",
          },
        ],
        customAttributes: [
          {
            key: "autoGeneratedPrice",
            value: "false",
          },
          {
            key: "isBlockchainUsed",
            value: "null",
          },
        ],
        categories: [
          {
            path: "freegames",
          },
          {
            path: "games/edition/base",
          },
          {
            path: "games/edition",
          },
          {
            path: "games",
          },
        ],
        tags: [
          {
            id: "1395",
          },
          {
            id: "21894",
          },
          {
            id: "18777",
          },
          {
            id: "1370",
          },
          {
            id: "24570",
          },
          {
            id: "9547",
          },
          {
            id: "16011",
          },
          {
            id: "1117",
          },
          {
            id: "1294",
          },
          {
            id: "18607",
          },
        ],
        catalogNs: {
          mappings: [
            {
              pageSlug: "adios-b378b4",
              pageType: "productHome",
            },
          ],
        },
        offerMappings: [
          {
            pageSlug: "adios-b378b4",
            pageType: "productHome",
          },
        ],
        price: {
          totalPrice: {
            discountPrice: 1799,
            originalPrice: 1799,
            voucherDiscount: 0,
            discount: 0,
            currencyCode: "USD",
            currencyInfo: {
              decimals: 2,
            },
            fmtPrice: {
              originalPrice: "$17.99",
              discountPrice: "$17.99",
              intermediatePrice: "$17.99",
            },
          },
          lineOffers: [
            {
              appliedRules: [],
            },
          ],
        },
        promotions: {
          promotionalOffers: [],
          upcomingPromotionalOffers: [
            {
              promotionalOffers: [
                {
                  startDate: "2023-01-26T16:00:00.000Z",
                  endDate: "2023-02-02T16:00:00.000Z",
                  discountSetting: {
                    discountType: "PERCENTAGE",
                    discountPercentage: 0,
                  },
                },
              ],
            },
          ],
        },
      },
      {
        title: "Hell is Others",
        id: "c1735ab5600741489a3ed30ed18c8b2f",
        namespace: "bd75186521ab40b5840774b78bb287e3",
        description:
          "Hell is Others is an extraction horror PVPVE top-down shooter. Outside the safety of your apartment lies the noir hellscape of Century City. A city of endless night that straddles the line between reality and insanity. Explore, hunt and loot in a place where blood is currency.",
        effectiveDate: "2099-01-01T00:00:00.000Z",
        offerType: "BASE_GAME",
        expiryDate: null,
        status: "ACTIVE",
        isCodeRedemptionOnly: false,
        keyImages: [
          {
            type: "OfferImageWide",
            url: "https://cdn1.epicgames.com/spt-assets/0de2d0d8870f457eaf7c6bf8c64f7f9e/hell-is-others-86xt2.jpg",
          },
          {
            type: "OfferImageTall",
            url: "https://cdn1.epicgames.com/spt-assets/0de2d0d8870f457eaf7c6bf8c64f7f9e/hell-is-others-1ra3i.jpg",
          },
          {
            type: "Thumbnail",
            url: "https://cdn1.epicgames.com/spt-assets/0de2d0d8870f457eaf7c6bf8c64f7f9e/hell-is-others-1ra3i.jpg",
          },
        ],
        seller: {
          id: "o-hu7df4t3lr4taq6gyjq55bvd2lhg83",
          name: "A List Games",
        },
        productSlug: null,
        urlSlug: "580ee2e767fa40df99b5d5c6462c24e8",
        url: null,
        items: [
          {
            id: "22c948f770854afca53f82a89d1f3eec",
            namespace: "bd75186521ab40b5840774b78bb287e3",
          },
        ],
        customAttributes: [
          {
            key: "autoGeneratedPrice",
            value: "false",
          },
          {
            key: "isManuallySetViewableDate",
            value: "true",
          },
          {
            key: "isManuallySetPCReleaseDate",
            value: "true",
          },
          {
            key: "isBlockchainUsed",
            value: "false",
          },
        ],
        categories: [
          {
            path: "freegames",
          },
          {
            path: "games/edition/base",
          },
          {
            path: "games/edition",
          },
          {
            path: "games",
          },
        ],
        tags: [
          {
            id: "1203",
          },
          {
            id: "19847",
          },
          {
            id: "1080",
          },
          {
            id: "22776",
          },
          {
            id: "1083",
          },
          {
            id: "9547",
          },
          {
            id: "9549",
          },
        ],
        catalogNs: {
          mappings: [
            {
              pageSlug: "hell-is-others-789262",
              pageType: "productHome",
            },
          ],
        },
        offerMappings: [
          {
            pageSlug: "hell-is-others-789262",
            pageType: "productHome",
          },
        ],
        price: {
          totalPrice: {
            discountPrice: 1499,
            originalPrice: 1499,
            voucherDiscount: 0,
            discount: 0,
            currencyCode: "USD",
            currencyInfo: {
              decimals: 2,
            },
            fmtPrice: {
              originalPrice: "$14.99",
              discountPrice: "$14.99",
              intermediatePrice: "$14.99",
            },
          },
          lineOffers: [
            {
              appliedRules: [],
            },
          ],
        },
        promotions: {
          promotionalOffers: [],
          upcomingPromotionalOffers: [
            {
              promotionalOffers: [
                {
                  startDate: "2023-01-26T16:00:00.000Z",
                  endDate: "2023-02-02T16:00:00.000Z",
                  discountSetting: {
                    discountType: "PERCENTAGE",
                    discountPercentage: 0,
                  },
                },
              ],
            },
          ],
        },
      },
    ],
  },
};

export default data;
